[package]
name = "monit-tool"
version = "0.1.0"
edition = "2021"
authors = ["s00d <Virus191288@gmail.com>"]
description = "command-line utility written in Rust for working with GitHub Actions"
repository = "https://github.com/s00d/monit-tool"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "monit-tool"
path = "src/main.rs"

[dependencies]
crossterm = "0.27.0"
dialoguer = "0.11.0"
plotters = "0.3.5"
ratatui = "0.25.0"
rgb = "0.8.37"
sysinfo = "0.29.11"
termion = "2.0.3"
textplots = "0.8.4"
tui = "0.19.0"
